#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
from typing import Iterable, Protocol, runtime_checkable

from csde_data_schema import EventRecord, FrameState, MetricRecord, RunStatus


@runtime_checkable
class CSDEWriter(Protocol):
    def write_state(self, frame: FrameState) -> None: ...

    def write_event(self, event: EventRecord) -> None: ...

    def write_metric(self, metric: MetricRecord) -> None: ...

    def update_status(self, status: RunStatus) -> None: ...

    def close(self) -> None: ...


@runtime_checkable
class CSDEReader(Protocol):
    def poll_states(self) -> list[FrameState]: ...

    def poll_events(self) -> list[EventRecord]: ...

    def poll_metrics(self) -> list[MetricRecord]: ...

    def read_status(self) -> RunStatus | None: ...


@runtime_checkable
class SnapshotStore(Protocol):
    def write_snapshot(self, frame: FrameState) -> Path: ...

    def load_snapshot(self, snapshot_path: Path) -> FrameState: ...


@runtime_checkable
class ViewerAdapter(Protocol):
    def load_frame(self, frame: FrameState) -> None: ...

    def apply_events(self, events: list[EventRecord]) -> None: ...

    def update_metrics(self, metrics: list[MetricRecord]) -> None: ...


@runtime_checkable
class ExperimentRunner(Protocol):
    def initialize(self) -> None: ...

    def step(self) -> FrameState: ...

    def iter_events(self) -> Iterable[EventRecord]: ...

    def current_metrics(self) -> MetricRecord: ...

    def current_status(self) -> RunStatus: ...

    def finalize(self) -> None: ...
